version: "3"

volumes:

  stream_hadoop_namenode:
  stream_hadoop_datanode:
  stream_workspace:
    external: true
  stream_postgres:

services:

  db:
    container_name: stream_pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: newdb
    ports:
      - "5432:5432"
    volumes:
      - stream_postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: stream_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  hive:
    image: stream_hive
    container_name: stream_hive
    restart: always
    ports:
     - "54310:54310"
     - "54311:54311"
     - "9870:9870"
     - "5349:5349"
     - "5249:5249"
    volumes:
      - stream_hadoop_datanode:/opt/hadoop/hadoop_data/hdfs/datanode
      - stream_hadoop_namenode:/opt/hadoop/hadoop_data/hdfs/namenode

  spark:
    image: stream_spark
    container_name: stream_spark
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8081:8081"
      - "7000:7000"

  kafka:
    image: stream_kafka
    container_name: stream_kafka
    restart: always

